### ISSUE TITLE
באג ביצירת פונקציות עם שמות דומים

### ISSUE THREAD

**Issue by gkpln3** [ChavaScript/chavascript#14]
כאשר אני מנסה לייצר שתי יכולות שמיוצגות על ידי אותיות דומות בעברית, אני מקבל התנגשות בשמות, והיכולת האמיתית לא נקראת

קלט:
```
יכולת סה() {
    בקרה.תעד(״שלום סה״);
}
יכולת ש() {
    בקרה.תעד(״שלום ש״);
}
סה();
ש();
```

פלט:
```
שלום ש
שלום ש
```

**Comment by avivcarmis** [comment]
@gkpln3 yes your'e right, i've also seen similar complaints on social media. i'll work on it, it's an easy fix, just need to make [this dictionary](https://github.com/ChavaScript/chavascript/blob/master/src/localization_settings.js#L218) חד חד ערכי.
Obviously, feel free to open a PR if you like to be a contributor ❤️

**Comment by eternaleclipse** [comment]
That won't solve the core problem - converting directly to English characters will create namespace collisions.
For instance, try creating a variable called ```ואר```.

Or something like:
```js
קבוע א = גטאג
בקרה.תעד(א)
```

**Comment by avivcarmis** [comment]
@eternaleclipse yes, that also a valid point. It's possible to try and just leave the Hebrew symbol names as it will still execute. 
![image](https://user-images.githubusercontent.com/9780481/103484812-403f8700-4dfa-11eb-931e-1e3f2298054b.png)

I'd actually prefer adding additional layer of translation that (after the current one) checks against JS keywords and rename if needed. I.e. today we do `ואר -> var` which breaks, i suggest `ואר -> var -> _var` or something of this sort. WDYT?

**Comment by eternaleclipse** [comment]
I think what you wanna do in this situation is create a simple one-to-one "hash" function.

You can ensure there are no collisions between inputs and other JS variables, by:
- Using a prefix like ```chvscr_``` for Chavascript identifiers to avoid colliding with things like ```gtag```
- Making the dictionary one-to-one, no duplicates and fixed (1 char) length for every value (avoid things like ש = sh)

Btw, your comment has me thinking about how to implement eval (הערך?) support, but that is an entirely different discussion :)

**Comment by gkpln3** [comment]
You could instead just prefix each name with a constant string, this would prevent the conflict with keywords (as long as you choose a prefix that's not included in any keyword).

Another option is to ditch the type names and just hash the Hebrew string and add a prefix to prevent it outputting a name starting with a number, but this would cause the resulting code to be very unreadalble.

**Comment by avivcarmis** [comment]
So i opened 2 PRs as 2 possible solutions, originally i preferred the dictionary solution as the result code is much clearer, at this point i'm not sure because some chars cannot be translated 1:1 and still be meaningful. This way i ended up translating `ש` to `o` simply because `s` and `c` weren't available. If both results produce code this is not clear, i guess i lean towards the hash function as a more robust solution. What do you guys think? Have any favourite? Also feel free to suggest a better char dictionary or a better hash function or anything better, really 😁  @gkpln3 @eternaleclipse

**Comment by avivcarmis** [comment]
@eternaleclipse 

> Btw, your comment has me thinking about how to implement eval (הערך?) support, but that is an entirely different discussion :)

Carry on...... 🤔 You have me curious. Or open a new issue for it if you prefer.

**Comment by Aminadav** [comment]
עוד דוגמא לבעיה
![image](https://user-images.githubusercontent.com/3584317/103589304-c68bc400-4ef3-11eb-9142-e560c1488a31.png)

**Comment by marmor7** [comment]
couldn't open a PR with my fix... so attaching a zipped patch file.

should maintain the same level of readability but prevent name-collisions

[alphabet3.diff.zip](https://github.com/ChavaScript/chavascript/files/5768572/alphabet3.diff.zip)

**Comment by avivcarmis** [comment]
@marmor7 I think it's a very cool idea, but since we're trying to avoid Hebrew chars in the output code, i'd also try to avoid any non-ascii char as well. We ended up adopting a combination of the two methods - translating literally for code readability in combination with a simple hash function to enhance uniqueness. We've also added a constant prefix as initially suggested by both @gkpln3 & @eternaleclipse, it's actually not required due to the hash functions but i don't think it decreases readability. The result looks like this:
<img width="898" alt="Screen Shot 2021-01-06 at 19 04 51" src="https://user-images.githubusercontent.com/9780481/103801554-8bee6c80-5056-11eb-92aa-234946d688e3.png">

**Comment by avivcarmis** [comment]
Thanks to @gkpln3 @eternaleclipse @dorilahav @elisherer @marmor7 for contributing to this discussion, I hope the chosen solution is acceptable to everyone 🙏

**Comment by avivcarmis** [comment]
Apparently the hash function could also return negative values 🤦‍♀️ 
I patched it with `Math.abs` for now

**Comment by gkpln3** [comment]
שמח מאוד לשמוע שהבעיה אכן תוקנה :) 
שים לב שפונקציית ההאש מוציאה פלט יחסית קצר ויכולה להביא אותך שוב למצב של התנגשויות בהנתן כמות משתנים גדולה.

חוץ מזה, הקוד המקומפל כבר לא יפה :(
אפשר בתור פתרון אלטרנטיבי:
א. לקצר את הprefix למשהו קצר יותר, נגיד c_
ב. לייצר את כל הast ולבדוק עליו האם יהיו התנגשויות (כלומר האם יש שני ערכים שיובילו לאותו תרגום אנגלי) ורק בהנחה שהם קיימים, להוסיף להם hash.
בדרך הזאת גם נפתור את בעיית הכפילויות (ונאפשר תרגום של קוד רב מג'ווהסקריפט לחווה סקריפט) וגם נוכל לשמור על הדוגמאות באתר כיפיות וקלילות, כמו הפונקציה "lvrh".
:)

**Comment by elisherer** [comment]
@gkpln3 הסיכוי שהתרגום הליטרלי וההאש יהיו זהים שואף לאפס

@avivcarmis 
אני מסכים שזה נהיה ארוך מאוד, מציע לעשות למספר שחוזר מהפונקציית האש (אחרי abs)
.toString(36)
זה אמור להיות תקין סינטקטי וקצר בהרבה יותר וכל עוד תמיד יש את התוספת אחרי\לפני של ההאש אפשר לוותר על התחילית (כי אי אפשר לגרום להתנגשות יותר) אז כדאי לשים את ההאש בסוף.
